apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  environment: dev
  project: devops-example

images:
  - name: FRONTEND_IMAGE
    newName: <terraform-output ecr_repository_urls["frontend"]>
    newTag: latest