apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: starter-kit

data:
  APP_NAME: DevOps Starter Kit
  APP_ENV: local
  LOG_LEVEL: INFO
  JWT_EXPIRE_MINUTES: "60"
  CORS_ORIGINS: http://starter.local
  MONGO_DATABASE: devopsstarter