apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: starter-kit

type: Opaque

stringData:
  MONGODB_URI: mongodb+srv://jpnishath:Gopika53435@cluster0.suh2bqf.mongodb.net/?appName=Cluster0
  JWT_SECRET_KEY: CHANGE_ME_SUPER_SECRET_KEY
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"