apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: starter-kit

type: Opaque

stringData:
  MONGODB_URI: MONGODB_URI
  JWT_SECRET_KEY: JWT_SECRET_KEY
  ACCESS_TOKEN_EXPIRE_MINUTES: ACCESS_TOKEN_EXPIRE_MINUTES