apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: backend-secrets
  namespace: apps

spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "demo-eks/backend/mongodb-uri"
        objectType: "secretsmanager"

  secretObjects:
    - secretName: backend-secret
      type: Opaque
      data:
        - objectName: "demo-eks/backend/mongodb-uri"
          key: MONGODB_URI