apiVersion: v1
kind: ServiceAccount

metadata:
  name: backend-sa
  namespace: apps

  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: argocd
    environment: dev
    project: starter

  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/backend-irsa-role

automountServiceAccountToken: true